### ISSUE TITLE
Просьба проверить домашнее задание "Контрактное Программирование"

### ISSUE THREAD

**Issue by boldevelop** [JSMonk/typing-practice#4]
Ветка: [add-login-service-contracts](https://github.com/boldevelop/typing-practice/tree/add-login-service-contracts)

**Comment by JSMonk** [comment]
Здравствуйте, Владислав.
1. Давайте вынесем [эти](https://github.com/JSMonk/typing-practice/compare/homework-task...boldevelop:add-login-service-contracts#diff-5aa05bd2c4579e4fa6216d4af98e4dd261bb5dc477d01e22edb273a1eba0b131R13) сущности каждую в свой файл.
2. Давайте также вынесем [эту часть логики](https://github.com/JSMonk/typing-practice/compare/homework-task...boldevelop:add-login-service-contracts#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR11) внутрь `UserService`, что бы не нарушать единство ответственности.
3. Кажется, [этот файл](https://github.com/JSMonk/typing-practice/compare/homework-task...boldevelop:add-login-service-contracts#diff-d3241f89a42184c562eb2e93e2e41d2d7e41e855fe54ec0bfcd2294bcd4ffb6cR1) уже не нужен 😄 

Остально прям отлично. Хорошая работа 👍🏻

**Comment by boldevelop** [comment]
Спасибо!
Исправил по пунктам:
1. Вынес в отдельные файлы
2. Вынес в метод [getUserByPassAndEmali](https://github.com/JSMonk/typing-practice/compare/homework-task...boldevelop:add-login-service-contracts#diff-096045fcc15e15c86099818c37598b123dd4e9cf6d9d265213b0f1c4b6858808R47), так же думал стоит ли передавать `users: readonly User[],` как аргумент или запрашивать в этом же методе список юзеров. Сделал аргументом функции из расчета, что метод может быть использован со списком пользователей отличающимся от запрашиваемого. Так же возник вопрос как можно допустим описать контракт в `runtypes` для метода класса, идея была определить [функцию](https://github.com/JSMonk/typing-practice/compare/homework-task...boldevelop:add-login-service-contracts#diff-096045fcc15e15c86099818c37598b123dd4e9cf6d9d265213b0f1c4b6858808R9) через `Contract` и вызывать ее в методе:
`getUserByPassAndEmali(
    users: readonly User[],
    email: Email,
    password: Password
  ): User {
    return getUserByPassAndEmali(users, email, password);
}
`
3. Удалил и также убрал метод [getConstructorByRole](https://github.com/JSMonk/typing-practice/compare/homework-task...boldevelop:add-login-service-contracts#diff-096045fcc15e15c86099818c37598b123dd4e9cf6d9d265213b0f1c4b6858808L47) он походу тоже уже не нужен)

**Comment by JSMonk** [comment]
Здравствууйте, Владислав.
Все красиво, задание принято.
Хорошая работа 👍🏻
